[target.x86_64-unknown-linux-musl]
linker = "/opt/homebrew/opt/musl-cross/bin/x86_64-linux-musl-gcc"
ar     = "/opt/homebrew/opt/musl-cross/bin/x86_64-linux-musl-ar"

[target.aarch64-unknown-linux-musl]
linker = "/opt/homebrew/opt/musl-cross/bin/aarch64-linux-musl-gcc"
ar     = "/opt/homebrew/opt/musl-cross/bin/aarch64-linux-musl-ar"

[profile.release]
opt-level     = 3
lto           = true
codegen-units = 1
strip         = true
