use clap::{Parser, Subcommand};
use std::path::PathBuf;

#[derive(Parser)]
#[command(
    name = "via",
    about = "Virtuoso IPC bridge — punches through layers like a via",
    long_about = None,
)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Subcommand)]
pub enum Command {
    /// Start the bridge server (launched by Virtuoso via ipcBeginProcess)
    Serve(ServeArgs),
    /// Bridge Virtuoso ipcWriteProcess output to the callback socket
    Forward(ForwardArgs),
    /// Send a SKILL expression to a running bridge server
    Send(SendArgs),
}

#[derive(clap::Args, Debug)]
pub struct ServeArgs {
    /// Unix socket path to listen on for `via send` clients
    #[arg(long, default_value_t = default_sock())]
    pub sock: String,

    /// Callback socket path (serve binds; forward connects)
    #[arg(long)]
    pub cb_sock: String,

    /// Token for callback channel authentication (generated by SKILL)
    #[arg(long)]
    pub cb_token: String,

    /// Shared secret for `via send` client authentication (empty = no auth)
    #[arg(long, default_value = "")]
    pub secret: String,

    /// Log file path (stdout/stderr must stay silent — Virtuoso captures them)
    #[arg(long, default_value = "via.log")]
    pub log_file: PathBuf,
}

#[derive(clap::Args, Debug)]
pub struct ForwardArgs {
    /// Callback socket path to forward to
    #[arg(long)]
    pub cb_sock: String,

    /// Token prepended to each forwarded line
    #[arg(long)]
    pub cb_token: String,

    /// Log file path
    #[arg(long, default_value = "via-forward.log")]
    pub log_file: PathBuf,
}

#[derive(clap::Args, Debug)]
pub struct SendArgs {
    /// Target bridge server socket path
    #[arg(long, default_value_t = default_sock())]
    pub sock: String,

    /// Shared secret for authentication (must match server --secret)
    #[arg(long, default_value = "")]
    pub secret: String,

    /// SKILL expression to evaluate
    #[arg(long)]
    pub expr: String,

    /// Fire-and-forget: do not wait for a result
    #[arg(long = "async")]
    pub no_wait: bool,
}

fn default_sock() -> String {
    let user = std::env::var("USER").unwrap_or_else(|_| "user".to_string());
    format!("/tmp/via-{user}.sock")
}
