use clap::{ArgGroup, Parser, Subcommand};
use std::path::PathBuf;

#[derive(Parser)]
#[command(
    name = "via",
    about = "Virtuoso IPC bridge — punches through layers like a via",
    long_about = None,
)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Subcommand)]
pub enum Command {
    /// Start the bridge server (launched by Virtuoso via ipcBeginProcess)
    Serve(ServeArgs),
    /// Bridge Virtuoso ipcWriteProcess output to the callback socket
    Forward(ForwardArgs),
    /// Send a SKILL expression or file to a running bridge server
    Send(SendArgs),
    /// Launch a managed Virtuoso instance in the background
    Start(StartArgs),
    /// List all managed Virtuoso instances
    List(ListArgs),
    /// Kill a managed Virtuoso instance
    Kill(KillArgs),
}

#[derive(clap::Args, Debug)]
pub struct ServeArgs {
    /// Unix socket path to listen on for `via send` clients
    #[arg(long, default_value_t = default_sock())]
    pub sock: String,

    /// Callback socket path (serve binds; forward connects)
    #[arg(long)]
    pub cb_sock: String,

    /// Token for callback channel authentication (generated by SKILL)
    #[arg(long)]
    pub cb_token: String,

    /// Shared secret for client authentication (omit to disable auth)
    #[arg(long, default_value = "")]
    pub secret: String,

    /// Log file path (stdout/stderr must stay silent — Virtuoso captures them)
    #[arg(long, default_value = "via.log")]
    pub log_file: PathBuf,
}

#[derive(clap::Args, Debug)]
pub struct ForwardArgs {
    /// Callback socket path to forward to
    #[arg(long)]
    pub cb_sock: String,

    /// Token prepended to each forwarded line
    #[arg(long)]
    pub cb_token: String,

    /// Log file path
    #[arg(long, default_value = "via-forward.log")]
    pub log_file: PathBuf,
}

#[derive(clap::Args, Debug)]
#[command(group(
    ArgGroup::new("input")
        .required(true)
        .args(["eval", "load"])
))]
pub struct SendArgs {
    /// Instance name (looks up socket and secret from the managed registry)
    #[arg(long)]
    pub name: Option<String>,

    /// Target bridge server socket path (ignored when --name is given)
    #[arg(long, default_value_t = default_sock())]
    pub sock: String,

    /// Shared secret for authentication (ignored when --name is given)
    #[arg(long, default_value = "")]
    pub secret: String,

    /// SKILL expression to evaluate
    #[arg(long)]
    pub eval: Option<String>,

    /// Load and execute a SKILL file (equivalent to load("path"))
    #[arg(long)]
    pub load: Option<PathBuf>,

    /// Fire-and-forget: do not wait for a result
    #[arg(long = "async")]
    pub no_wait: bool,

    /// Print what would be sent without connecting to the bridge
    #[arg(long)]
    pub dry_run: bool,
}

#[derive(clap::Args, Debug)]
pub struct StartArgs {
    /// Unique name for this Virtuoso instance
    #[arg(long)]
    pub name: String,

    /// Working directory for the Virtuoso process (default: current directory)
    #[arg(long)]
    pub workspace: Option<PathBuf>,

    /// Path to the `virtuoso` binary (default: `virtuoso` from PATH)
    #[arg(long, default_value = "virtuoso")]
    pub virtuoso: String,

    /// Run Virtuoso without a GUI (passes -nograph)
    #[arg(long)]
    pub nograph: bool,

    /// Print what would happen without writing files or spawning Virtuoso
    #[arg(long)]
    pub dry_run: bool,
}

#[derive(clap::Args, Debug)]
pub struct ListArgs {
    /// Remove dead entries from the registry
    #[arg(long)]
    pub prune: bool,

    /// Print what would be pruned without modifying the registry
    #[arg(long)]
    pub dry_run: bool,
}

#[derive(clap::Args, Debug)]
pub struct KillArgs {
    /// Name of the instance to kill
    pub name: String,

    /// Send SIGKILL instead of SIGTERM
    #[arg(long)]
    pub force: bool,

    /// Print what would happen without sending any signal or modifying the registry
    #[arg(long)]
    pub dry_run: bool,
}

fn default_sock() -> String {
    let user = std::env::var("USER").unwrap_or_else(|_| "user".to_string());
    format!("/tmp/via-{user}.sock")
}
